//? Client-side E2E-style encryption using Web Crypto API (AES-GCM + PBKDF2)
// Messages are encrypted in the browser before being written to Firestore,
// and decrypted in the browser after being read. The passphrase never leaves the client.

// Shared TextEncoder and TextDecoder instances for converting UTF-8 strings to/from Uint8Array byte buffers
const enc = new TextEncoder();
const dec = new TextDecoder();

/**
 * Converts a Uint8Array or ArrayBuffer into a Base64-encoded string for safe network storage/transmission.
 * @param bytes Raw byte array or ArrayBuffer
 * @returns Base64 string representation
 */
function toBase64(bytes: ArrayBuffer | Uint8Array): string {
  const arr = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);
  let binary = "";
  arr.forEach((b) => (binary += String.fromCharCode(b)));
  return btoa(binary);
}

/**
 * Converts a Base64-encoded string back into a Uint8Array byte array.
 * @param b64 Base64 string representation
 * @returns Uint8Array containing raw byte data
 */
function fromBase64(b64: string): Uint8Array {
  const binary = atob(b64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

/**
 * Derives a 256-bit AES-GCM CryptoKey from a user passphrase and salt (e.g. room name) using PBKDF2.
 * Key derivation is computationally hardened with 150,000 SHA-256 iterations to resist brute-force attacks.
 * 
 * @param passphrase Secret user passphrase entered in client UI
 * @param salt Unique string (e.g., room name) used to isolate key generation across contexts
 * @returns Promise resolving to a non-extractable CryptoKey usable for encryption and decryption
 */
export async function deriveKey(
  passphrase: string,
  salt: string,
): Promise<CryptoKey> {
  // Import the raw passphrase string as a key usable by PBKDF2
  const baseKey = await crypto.subtle.importKey(
    "raw",
    enc.encode(passphrase),
    "PBKDF2",
    false,
    ["deriveKey"],
  );

  // Derive the 256-bit AES-GCM symmetric key
  return crypto.subtle.deriveKey(
    {
      name: "PBKDF2",
      salt: enc.encode(salt),
      iterations: 150_000,
      hash: "SHA-256",
    },
    baseKey,
    { name: "AES-GCM", length: 256 },
    false,
    ["encrypt", "decrypt"],
  );
}

/**
 * Encrypts plaintext message into a combined format string: "ivBase64:cipherBase64".
 * Uses a cryptographically secure random 96-bit (12-byte) Initialisation Vector (IV) for every invocation.
 * 
 * @param text Plaintext message string
 * @param key AES-GCM CryptoKey generated by deriveKey
 * @returns Promise resolving to serialized payload string ("IV:Ciphertext")
 */
export async function encryptText(
  text: string,
  key: CryptoKey,
): Promise<string> {
  // Generate a random 12-byte Initialization Vector (IV) required by AES-GCM
  const iv = crypto.getRandomValues(new Uint8Array(12));
  
  // Encrypt the encoded plaintext bytes using AES-GCM
  const cipherBuf = await crypto.subtle.encrypt(
    { name: "AES-GCM", iv },
    key,
    enc.encode(text),
  );

  // Return formatted payload combining Base64 IV and Base64 Ciphertext separated by a colon
  return `${toBase64(iv)}:${toBase64(cipherBuf)}`;
}

/**
 * Decrypts a "ivBase64:cipherBase64" payload back into the original plaintext message string.
 * Throws an error if the ciphertext is malformed, corrupted, or if the key/passphrase is wrong.
 * 
 * @param payload Serialized string in "IV:Ciphertext" format
 * @param key AES-GCM CryptoKey derived from the correct passphrase
 * @returns Promise resolving to original plaintext message string
 */
export async function decryptText(
  payload: string,
  key: CryptoKey,
): Promise<string> {
  const [ivB64, cipherB64] = payload.split(":");
  if (!ivB64 || !cipherB64) throw new Error("Malformed ciphertext");

  // Reconstruct byte arrays from Base64 strings
  const iv = fromBase64(ivB64);
  const cipherBuf = fromBase64(cipherB64);

  // Decrypt ciphertext buffer back to raw plaintext bytes using AES-GCM
  const plainBuf = await crypto.subtle.decrypt(
    { name: "AES-GCM", iv },
    key,
    cipherBuf,
  );

  // Decode bytes to UTF-8 plaintext string
  return dec.decode(plainBuf);
}
